name: Release version

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Get tag value
        id: tag
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "Working tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  build-push:
    name: Build and Push Dockerfile to GitHub Packages
    needs:
      - prepare
    if: ${{ needs.prepare.outputs.tag }}
    uses: ./.github/workflows/reusable-build-and-push-github-packages.yml
    with:
      context: .
      dockerfile: Dockerfile
      image-repo: ghcr.io/gaze-network/atomicals-electrumx
      image-tag: ${{ needs.prepare.outputs.tag }}
