name: Release version

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Get tag value
        id: tag
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "Working tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  build-push:
    name: Build and Push Dockerfile to GitHub Packages
    needs:
      - prepare
    if: ${{ needs.prepare.outputs.tag }}
    uses: ./.github/workflows/reusable-build-and-push-github-packages.yml
    with:
      context: .
      dockerfile: Dockerfile
      image-repo: ghcr.io/gaze-network/atomicals-electrumx
      image-tag: ${{ needs.prepare.outputs.tag }}

  release-note:
    name: Draft release note
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare note
        run: git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n  * %an <%ae>' --no-merges >> ".github/RELEASE-TEMPLATE.md"

      - name: Create draft release note
        uses: softprops/action-gh-release@v2
        with:
          body_path: ".github/RELEASE-TEMPLATE.md"
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
