name: Build and Push Dockerfile to GitHub Packages

on:
  workflow_call:
    inputs:
      context:
        description: Path to build context
        required: true
        type: string
        default: "."
      dockerfile:
        description: Path to Dockerfile
        required: true
        type: string
        default: "Dockerfile"
      image-repo:
        description: Repository for the image
        required: true
        type: string
      image-tag:
        description: Tag for the image
        required: true
        type: string
    outputs:
      image-tag:
        description: Full image tag of result image
        value: ${{ jobs.build-push.outputs.image-tag }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: "${{ inputs.image-repo }}:${{ inputs.image-tag }}"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          tags: "${{ inputs.image-repo }}:${{ inputs.image-tag }}"
          cache-from: type=registry,ref=${{ inputs.image-repo }}:buildcache
          cache-to: type=registry,ref=${{ inputs.image-repo }}:buildcache,mode=max
